name: Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Necesario para push desde PRs del mismo repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ github.event_name == 'pull_request' && format('ghcr.io/{0}/panal:pr-{1}-{2}', github.repository_owner, github.event.number, github.sha) || format('ghcr.io/{0}/panal:{1}', github.repository_owner, 'latest') }}
            ${{ github.event_name == 'pull_request' && '' || format('ghcr.io/{0}/panal:{1}', github.repository_owner, github.sha) }}
          labels: |
            type=${{ github.event_name }}
            pr=${{ github.event_name == 'pull_request' && github.event.number || 'none' }}
            branch=${{ github.ref_name }}
          cache-from: type=gha
          cache-to: ${{ github.event_name == 'pull_request' && 'type=gha,mode=max' || 'type=gha,mode=max' }}
